--- #YAML:1.0
name:                WebService-Google-Language
version:             0.09
abstract:            Perl interface to the Google AJAX Language API
license:             perl
author:              
    - Henning Manske <hma@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    JSON:                          2
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
